config/routes.rb
Rails.application.routes.draw do
  resources :attachments
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :statuses
  resources :watches
  resources :votes
  
  resources :issues do
     member do
         get "set_status", to: "issues#set_status", :as => :set_status

     
     end
  end
  
  resources :comments do
    member do
    get "destroy", to: "comments#destroy", :as => :destroy
    get "pin_to_top", to: "comments#pin_to_top", :as => :pin_to_top
    get "unpin_to_top", to: "comments#unpin_to_top", :as => :unpin_to_top
  
    end
  end



  root to: "home#show"
  
  scope '/currentuser' do
    get '/' => 'users#currentuser'
  end
  
  scope '/api' do
    scope '/v1' do
      scope '/issues' do
        get '/' => 'issues_api#index'
        post '/' => 'issues_api#new'
        scope '/:id' do
          scope '/vote' do
            delete '/' => 'issues_api#deleteVote'
          end
          scope '/watch' do
            delete '/' => 'issues_api#deleteWatch'
          end
          get '/' => 'issues_api#show'
          put '/' => 'issues_api#edit'
          delete '/' => 'issues_api#delete'
          
          scope '/attachments' do
            get '/' => 'issues_api#get_attachments'
            post '/' => 'issues_api#add_attachment'
          end
          scope '/set_status' do
            post '/' => 'issues_api#set_status'
          end
        end
      end
      scope '/comments' do
        post '/' => 'comments_api#create'
        scope '/:id' do
          get '/' => 'comments_api#show'
          delete '/' => 'comments_api#destroy'
          scope '/pin_to_top' do
            put '/' => 'comments_api#pin_to_top'
          end
          scope '/unpin_to_top' do
            put '/' => 'comments_api#unpin_to_top'
          end
        end
      end
      scope '/users' do
        get '/' => 'users_api#get_all_users'
        scope '/currentuser' do
          get '/' => 'users_api#currentApiKeyUser'
        end
        scope '/:id' do
          get '/' => 'users_api#show'
        end
      end
      scope '/votes' do
        post '/' => 'votes_api#create'
        scope '/:id' do
          delete '/' => 'votes_api#destroy'
        end
      end
      scope '/watches' do
        post '/' => 'watches_api#create'
        scope '/:id' do
          delete '/' => 'watches_api#destroy'
        end
      end
    end
   end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :creator, :class_name => 'User', :foreign_key => 'author_id'
  belongs_to :issue, :class_name => 'Issue', :foreign_key => 'issue_id'

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(:author_id => session[:user_id], :issue_id => params[:issue_id], :text => comment_params[:text], pin_to_top:0)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { redirect :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def pin_to_top
    @hihapin = Comment.where("pin_to_top = ? AND issue_id = ?", 1, params[:issue_id]).first
    if @hihapin != nil
      Comment.update(@hihapin.id, :pin_to_top => 0)
    end
    respond_to do |format|
      if Comment.update(params[:id], :pin_to_top => 1, :issue_id => params[:issue_id])
        format.html { redirect_to :back, notice: 'pin to top was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
         format.html { render :edit }
         format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end  
  
  
  def unpin_to_top
      respond_to do |format|
      if Comment.update(params[:id], :pin_to_top => 0)
        format.html { redirect_to :back, notice: 'unpin to top was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end  

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
        format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
    end
    
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author_id, :text, :issue_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_id %>
    <%= f.number_field :author_id %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :issue_id %>
    <%= f.number_field :issue_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Text</th>
      <th>Issue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author_id %></td>
        <td><%= comment.text %></td>
        <td><%= comment.issue_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @comment.issue_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>